name: hcslzapp
description: The Harley Club Slz Project

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  path: ^1.8.0
  http: ^0.13.4
  http_interceptor: ^1.0.2
  url_launcher: ^6.0.17
  table_calendar: ^2.3.3
  intl: ^0.17.0
  google_maps_flutter: ^2.1.1
  flutter_launcher_icons: ^0.9.2
  flare_flutter: ^3.0.2
  mobx: ^2.0.6+1
  flutter_mobx: ^2.0.3+2
  asuka: ^2.0.0
  mask_text_input_formatter: ^2.0.0
  jwt_decode: ^0.3.1
  glutton: ^2.0.0
  image_picker: ^0.8.4+4
  firebase_storage: ^10.2.4
  firebase_core: ^1.10.6
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.1.6
  circular_countdown_timer: ^0.2.0

  #table_calendar: ^3.0.3
  #splashscreen: ^1.3.5
  #provider: ^4.3.3

flutter_icons:
  image_path: "assets/icons/logo.png"
  android: true
  ios: true

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  # cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.7
  mobx_codegen: ^2.0.5+2


# Splash Screen Settings
flutter_native_splash:
  #general
  #background_image: assets/imgs/logo.png
  color: "#fdd7cb"
  android: true
  ios: true
  android_12:
    image: assets/imgs/logo.png
    # icon_background_color: "#FFD1A6"


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/imgs/noImage.png
    - assets/imgs/user.png
    - assets/imgs/logo.png
    - assets/imgs/logo_carteirad.png
    - assets/imgs/logo_login.png
    - assets/imgs/backlogo.png
    - assets/imgs/hdlogo.png
    - assets/imgs/docs.png
    - assets/imgs/eventos.png
    - assets/imgs/financeiro.png
    - assets/imgs/carteirad.png
    - assets/imgs/parcerias.png
    - assets/imgs/boutique.png
    - assets/imgs/classificados.png
    - assets/imgs/ladies.jpg
    - assets/imgs/oficina.png
    - assets/imgs/codigosdtc.png
    - assets/imgs/maps.png
    - assets/imgs/sobre.jpeg
    - assets/imgs/dependentes.png
    - assets/imgs/motocicletas.png

    #
    - assets/icons/digital-logo.png
    - assets/icons/instagram-logo.png
    - assets/icons/instagram-logo-disabled.png
    - assets/icons/mail-logo.png
    - assets/icons/mail-logo-disabled.png
    - assets/icons/telephone-logo-1.png
    - assets/icons/telephone-logo-1-disabled.png
    - assets/icons/telephone-logo-2.png
    - assets/icons/telephone-logo-2-disabled.png
    - assets/icons/facebook-logo.png
    - assets/icons/facebook-logo-disabled.png
    - assets/icons/whatsapp-logo.png
    - assets/icons/whatsapp-logo-disabled.png
    - assets/icons/google-maps-logo.png
    - assets/icons/google-maps-logo-disabled.png
    - assets/icons/site-institucional-logo.png
    - assets/icons/site-institucional-logo-disabled.png
    - assets/icons/pdf-logo.png
    - assets/icons/pdf-logo_v2.png
    - assets/icons/pdf-logo_v2-disabled.png
    - assets/icons/info-icon.png
    - assets/icons/discount.png
    - assets/icons/logo.png

    #
    - assets/anims/splash.flr




  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
